import Foundation
import RaycastSwiftMacros

struct ListItem: Codable {
  let id: String
  let title: String
  let subtitle: String
}

@raycast
func getItems() -> [ListItem] {
  return [
    ListItem(id: "1", title: "Swift Item One", subtitle: "Generated by Swift"),
    ListItem(id: "2", title: "Swift Item Two", subtitle: "From native code"),
    ListItem(id: "3", title: "Swift Item Three", subtitle: "Fast and safe"),
  ]
}

@raycast
func greet(name: String) -> String {
  return "Hello, \(name)! Greetings from Swift."
}
