import { pascalCase } from 'change-case'

// Semantic unicode mapping for Raycast icon IDs.
// Uses ONLY characters from emoji-safe unicode ranges for consistent terminal text rendering.
// Safe ranges used: Arrows (U+2190), Math Operators (U+2200), Geometric Shapes (U+25A0,
// excluding U+25B6/U+25C0), Block Elements (U+2580), Misc Technical non-emoji subset,
// Box Drawing (U+2500), Letterlike Symbols, General Punctuation, Latin/ASCII.
const ICON_MAP: Record<string, string> = {
  'add-person-16': '⊕',
  'airplane-16': '↗',
  'airplane-filled-16': '↗',
  'airplane-landing-16': '↘',
  'airplane-takeoff-16': '↗',
  'airpods-16': '⊚',
  'alarm-16': '⌀',
  'alarm-ringing-16': '⌀',
  'align-centre-16': '≡',
  'align-left-16': '≡',
  'align-right-16': '≡',
  'american-football-16': '◇',
  'anchor-16': '⊥',
  'app-window-16': '⊞',
  'app-window-grid-2x2-16': '⊞',
  'app-window-grid-3x3-16': '⊞',
  'app-window-list-16': '≡',
  'app-window-sidebar-left-16': '◧',
  'app-window-sidebar-right-16': '◨',
  'arrow-clockwise-16': '↻',
  'arrow-counter-clockwise-16': '↺',
  'arrow-down-16': '↓',
  'arrow-down-circle-16': '⇩',
  'arrow-down-circle-filled-16': '⇩',
  'arrow-left-16': '←',
  'arrow-left-circle-16': '⇦',
  'arrow-left-circle-filled-16': '⇦',
  'arrow-ne-16': '↗',
  'arrow-right-16': '→',
  'arrow-right-circle-16': '⇨',
  'arrow-right-circle-filled-16': '⇨',
  'arrow-up-16': '↑',
  'arrow-up-circle-16': '⇧',
  'arrow-up-circle-filled-16': '⇧',
  'arrows-contract-16': '⇤',
  'arrows-expand-16': '⇥',
  'at-symbol-16': '@',
  'band-aid-16': '╋',
  'bank-note-16': '¤',
  // 'bar-chart-16': '▊',
  // 'bar-code-16': '▐',
  'bath-tub-16': '▬',
  'battery-16': '▮',
  'battery-charging-16': '▮',
  'battery-disabled-16': '▯',
  'bell-16': '⍾',
  'bell-disabled-16': '⍻',
  'bike-16': '⎌',
  'binoculars-16': '⌕',
  'bird-16': '∿',
  'blank-document-16': '▯',
  'bluetooth-16': 'ᛒ',
  'boat-16': '≈',
  'bold-16': '𝐁',
  'bolt-16': '↯',
  'bolt-disabled-16': '↯',
  'book-16': '⊞',
  'bookmark-16': '▷',
  'box-16': '□',
  'brush-16': '⊘',
  'bug-16': '⊗',
  'building-16': '⌂',
  'bullet-points-16': '•',
  'bulls-eye-16': '◎',
  'bulls-eye-missed-16': '◌',
  'buoy-16': '◉',
  'calculator-16': '⊞',
  'calendar-16': '▦',
  'camera-16': '⌬',
  'car-16': '⊳',
  'cart-16': '⊲',
  'cd-16': '◎',
  'center-16': '⊡',
  'check-16': '✓',
  'check-circle-16': '✓',
  'check-list-16': '✓',
  'check-rosette-16': '✓',
  'checkmark-16': '✓',
  'chess-piece-16': '⊠',
  'chevron-down-16': '⌄',
  'chevron-down-small-16': '⌄',
  'chevron-left-16': '‹',
  'chevron-left-small-16': '‹',
  'chevron-right-16': '›',
  'chevron-right-small-16': '›',
  'chevron-up-16': '⌃',
  'chevron-up-down-16': '⇕',
  'chevron-up-small-16': '⌃',
  'circle-16': '○',
  'circle-disabled-16': '⊘',
  'circle-ellipsis-16': '◯',
  'circle-filled-16': '●',
  'circle-progress-16': '◔',
  'circle-progress-100-16': '●',
  'circle-progress-25-16': '◔',
  'circle-progress-50-16': '◑',
  'circle-progress-75-16': '◕',
  'clear-formatting-16': '⌧',
  'clipboard-16': '⎘',
  'clock-16': '◴',
  'cloud-16': '◠',
  'cloud-lightning-16': '◠',
  'cloud-rain-16': '◠',
  'cloud-snow-16': '◠',
  'cloud-sun-16': '◠',
  'code-16': '⟨⟩',
  'code-block-16': '▤',
  'cog-16': '⊛',
  'coin-16': '¤',
  'coins-16': '¤',
  'command-symbol-16': '⌘',
  'compass-16': '◎',
  'computer-chip-16': '⎔',
  'contrast-16': '◑',
  'copy-clipboard-16': '⎘',
  'credit-card-16': '▬',
  'cricket-ball-16': '◉',
  'crop-16': '⌌',
  'crown-16': '△',
  'crypto-16': '₿',
  'delete-document-16': '⌧',
  'desktop-16': '⎚',
  'devices-16': '⎚',
  'dna-16': '⧖',
  'document-16': '▯',
  'dot-16': '·',
  'download-16': '⤓',
  'droplets-16': '≋',
  'duplicate-16': '⧉',
  'edit-shape-16': '⌑',
  'eject-16': '△',
  'ellipsis-16': '…',
  'ellipsis-vertical-16': '⋮',
  'emoji-16': '◠',
  'emoji-sad-16': '◡',
  'envelope-16': '▷',
  'eraser-16': '⌫',
  'exclamationmark-16': '!',
  'exclamationmark-2-16': '‼',
  'exclamationmark-3-16': '‼',
  'eye-16': '◉',
  'eye-disabled-16': '⊘',
  'eye-dropper-16': '⊙',
  'female-16': '⊕',
  'film-strip-16': '▥',
  'filter-16': '⧩',
  'finder-16': '⌕',
  'fingerprint-16': '◉',
  'flag-16': '⊳',
  'folder-16': '▤',
  'footprints-16': '⊹',
  'forward-16': '▸',
  'forward-filled-16': '▸',
  'fountain-tip-16': '⌑',
  'full-signal-16': '▊',
  'game-controller-16': '⊞',
  'gauge-16': '◔',
  'geopin-16': '⊙',
  'germ-16': '※',
  'gift-16': '⊠',
  'glasses-16': '∞',
  'globe-01-16': '⊕',
  'goal-16': '⊡',
  'hammer-16': '⊤',
  'hard-drive-16': '▬',
  'hashtag-16': '#',
  'heading-16': '𝐇',
  'headphones-16': '⊚',
  'heart-16': '◆',
  'heart-disabled-16': '◇',
  'heartbeat-16': '◆',
  'highlight-16': '▮',
  'hourglass-16': '⧖',
  'house-16': '⌂',
  'humidity-16': '≋',
  'image-16': '⊞',
  'important-01-16': '‼',
  'info-01-16': 'ℹ',
  'italics-16': '𝐼',
  'key-16': '⊢',
  'keyboard-16': '⌗',
  'layers-16': '◫',
  // 'leaderboard-16': '▊',
  'leaf-16': '∿',
  'light-bulb-16': '※',
  'light-bulb-off-16': '※',
  'line-chart-16': '⌒',
  'link-16': '∞',
  'livestream-01-16': '◉',
  'livestream-disabled-01-16': '◌',
  'lock-16': '⊟',
  'lock-disabled-16': '⊠',
  'lock-unlocked-16': '⊠',
  'logout-16': '⎋',
  'lorry-16': '⊳',
  'lowercase-16': 'aᵃ',
  'magnifying-glass-16': '⌕',
  'male-16': '⊕',
  'map-16': '▦',
  'mask-16': '◑',
  'maximize-16': '⤢',
  'medical-support-16': '╋',
  'megaphone-16': '⊳',
  'memory-stick-16': '▬',
  'microphone-16': '⊙',
  'microphone-disabled-16': '⊘',
  'minimize-16': '⤡',
  'minus-16': '−',
  'minus-circle-16': '⊖',
  'minus-circle-filled-16': '⊖',
  'mobile-16': '▯',
  'monitor-16': '⎚',
  'moon-16': '◐',
  'moon-down-16': '◐',
  'moon-up-16': '◐',
  'moonrise-16': '◐',
  'mountain-16': '△',
  'mouse-16': '⊙',
  'move-16': '⊹',
  'mug-16': '⊔',
  'mug-steam-16': '⊔',
  'multiply-16': '×',
  'music-16': '∿',
  'network-16': '⊕',
  'new-document-16': '▯',
  'new-folder-16': '▤',
  'number-list-16': '⑴',
  'paperclip-16': '⊶',
  'paragraph-16': '¶',
  'patch-16': '╋',
  'pause-16': '‖',
  'pause-filled-16': '‖',
  'pencil-16': '⌑',
  'person-16': '⊙',
  'person-circle-16': '⊙',
  'person-lines-16': '⊙',
  'phone-16': '⌕',
  'phone-ringing-16': '⌕',
  'pie-chart-16': '◔',
  'pill-16': '⊝',
  'pin-16': '⊙',
  'pin-disabled-16': '⊘',
  'play-16': '▸',
  'play-filled-16': '▸',
  'plug-16': '⊢',
  'plus-16': '+',
  'plus-circle-16': '⊕',
  'plus-circle-filled-16': '⊕',
  'plus-minus-divide-multiply-16': '±',
  'plus-square-16': '⊞',
  'plus-top-right-square-16': '⊞',
  'power-16': '⊙',
  'print-16': '⎙',
  'question-mark-circle-16': '?',
  'quicklink-16': '∞',
  'quotation-marks-16': '❝',
  'quote-block-16': '❝',
  'racket-16': '⊙',
  'raindrop-16': '≋',
  'raycast-logo-neg-16': '◆',
  'raycast-logo-pos-16': '◆',
  'receipt-16': '▯',
  'redo-16': '↻',
  'remove-person-16': '⊖',
  'repeat-16': '↻',
  'replace-16': '⇄',
  'replace-one-16': '⇄',
  'reply-16': '↩',
  'rewind-16': '◂',
  'rewind-filled-16': '◂',
  'rocket-16': '⁕',
  'rosette-16': '✦',
  'rotate-anti-clockwise-16': '↺',
  'rotate-clockwise-16': '↻',
  'rss-16': '◉',
  'ruler-16': '⊢',
  'save-document-16': '⊞',
  'shield-01-16': '⊛',
  'short-paragraph-16': '¶',
  'shuffle-16': '⇝',
  'signal-0-16': '▁',
  'signal-1-16': '▂',
  // 'signal-2-16': '▄',
  // 'signal-3-16': '█',
  'snippets-16': '⊠',
  'snowflake-16': '※',
  'soccer-ball-16': '◎',
  'speaker-16': '◁',
  'speaker-down-16': '◁',
  'speaker-high-16': '◂',
  'speaker-low-16': '◁',
  'speaker-off-16': '◃',
  'speaker-on-16': '◂',
  'speaker-up-16': '◂',
  'speech-bubble-16': '⊐',
  'speech-bubble-active-16': '⊐',
  'speech-bubble-important-16': '⊐',
  'square-ellipsis-16': '□',
  'stacked-bars-1-16': '▁',
  'stacked-bars-2-16': '▃',
  'stacked-bars-3-16': '▅',
  'stacked-bars-4-16': '▇',
  'star-16': '★',
  'star-circle-16': '★',
  'star-disabled-16': '☆',
  'stars-16': '✦',
  'stop-16': '■',
  'stop-filled-16': '■',
  'stopwatch-16': '◴',
  'store-16': '⊞',
  'strike-through-16': 'S̶',
  'sun-16': '※',
  'sunrise-16': '※',
  'swatch-16': '◧',
  'switch-16': '⇋',
  'syringe-16': '⊸',
  'tack-16': '⊙',
  'tack-disabled-16': '⊘',
  'tag-16': '⊢',
  'temperature-16': '⊥',
  'tennis-ball-16': '◎',
  'terminal-16': '>_',
  'text-16': '𝐓',
  'text-cursor-16': '⌶',
  'text-input-16': '⌗',
  'text-selection-16': '▮',
  'thumbs-down-16': '⊘',
  'thumbs-down-filled-16': '⊘',
  'thumbs-up-16': '✓',
  'thumbs-up-filled-16': '✓',
  'ticket-16': '▬',
  'torch-16': '※',
  'train-16': '⊳',
  'trash-16': '⌧',
  'tray-16': '⊔',
  'tree-16': '⊥',
  'trophy-16': '⊛',
  'two-people-16': '⊙',
  'umbrella-16': '△',
  'underline-16': 'U̲',
  'undo-16': '↺',
  'upload-16': '⤒',
  'uppercase-16': 'Aᴬ',
  'video-16': '▸',
  'video-disabled-16': '⊘',
  'wallet-16': '▬',
  'wand-16': '✧',
  'warning-16': '△',
  'waveform-16': '∿',
  'weights-16': '⊥',
  'wifi-16': '⊛',
  'wifi-disabled-16': '⊘',
  'wind-16': '≋',
  'windsock-16': '⊳',
  'wrench-screwdriver-16': '⊤',
  'wrist-watch-16': '◴',
  'x-mark-circle-16': '×',
  'x-mark-circle-filled-16': '×',
  'x-mark-circle-half-dash-16': '×',
  'x-mark-top-right-square-16': '×',
  'xmark-16': '×',
}

// Number icons (number-00-16 through number-99-16) use circled numbers where available,
// falling back to the plain digit string for values without unicode circled forms.
for (let i = 0; i <= 99; i++) {
  const id = `number-${String(i).padStart(2, '0')}-16`
  if (i >= 0 && i <= 20) {
    // Unicode circled numbers: ⓪①②…⑳
    ICON_MAP[id] = String.fromCodePoint(i === 0 ? 0x24EA : 0x2460 + i - 1)
  } else if (i <= 50) {
    // Unicode circled numbers 21-50: ㉑㉒…㊿
    ICON_MAP[id] = String.fromCodePoint(0x3251 + i - 21)
  } else {
    // No standard circled unicode above 50, use plain digits
    ICON_MAP[id] = String(i)
  }
}

const FALLBACK_ICON = '●'

export function getIconShape(iconId: string): string {
  return ICON_MAP[iconId] || FALLBACK_ICON
}

export const iconIds = [
  'add-person-16',
  'airplane-16',
  'airplane-filled-16',
  'airplane-landing-16',
  'airplane-takeoff-16',
  'airpods-16',
  'alarm-16',
  'alarm-ringing-16',
  'align-centre-16',
  'align-left-16',
  'align-right-16',
  'american-football-16',
  'anchor-16',
  'app-window-16',
  'app-window-grid-2x2-16',
  'app-window-grid-3x3-16',
  'app-window-list-16',
  'app-window-sidebar-left-16',
  'app-window-sidebar-right-16',
  'arrow-clockwise-16',
  'arrow-counter-clockwise-16',
  'arrow-down-16',
  'arrow-down-circle-16',
  'arrow-down-circle-filled-16',
  'arrow-left-16',
  'arrow-left-circle-16',
  'arrow-left-circle-filled-16',
  'arrow-ne-16',
  'arrow-right-16',
  'arrow-right-circle-16',
  'arrow-right-circle-filled-16',
  'arrow-up-16',
  'arrow-up-circle-16',
  'arrow-up-circle-filled-16',
  'arrows-contract-16',
  'arrows-expand-16',
  'at-symbol-16',
  'band-aid-16',
  'bank-note-16',
  'bar-chart-16',
  'bar-code-16',
  'bath-tub-16',
  'battery-16',
  'battery-charging-16',
  'battery-disabled-16',
  'bell-16',
  'bell-disabled-16',
  'bike-16',
  'binoculars-16',
  'bird-16',
  'blank-document-16',
  'bluetooth-16',
  'boat-16',
  'bold-16',
  'bolt-16',
  'bolt-disabled-16',
  'book-16',
  'bookmark-16',
  'box-16',
  'brush-16',
  'bug-16',
  'building-16',
  'bullet-points-16',
  'bulls-eye-16',
  'bulls-eye-missed-16',
  'buoy-16',
  'calculator-16',
  'calendar-16',
  'camera-16',
  'car-16',
  'cart-16',
  'cd-16',
  'center-16',
  'check-16',
  'check-circle-16',
  'check-list-16',
  'check-rosette-16',
  'checkmark-16',
  'chess-piece-16',
  'chevron-down-16',
  'chevron-down-small-16',
  'chevron-left-16',
  'chevron-left-small-16',
  'chevron-right-16',
  'chevron-right-small-16',
  'chevron-up-16',
  'chevron-up-down-16',
  'chevron-up-small-16',
  'circle-16',
  'circle-disabled-16',
  'circle-ellipsis-16',
  'circle-filled-16',
  'circle-progress-16',
  'circle-progress-100-16',
  'circle-progress-25-16',
  'circle-progress-50-16',
  'circle-progress-75-16',
  'clear-formatting-16',
  'clipboard-16',
  'clock-16',
  'cloud-16',
  'cloud-lightning-16',
  'cloud-rain-16',
  'cloud-snow-16',
  'cloud-sun-16',
  'code-16',
  'code-block-16',
  'cog-16',
  'coin-16',
  'coins-16',
  'command-symbol-16',
  'compass-16',
  'computer-chip-16',
  'contrast-16',
  'copy-clipboard-16',
  'credit-card-16',
  'cricket-ball-16',
  'crop-16',
  'crown-16',
  'crypto-16',
  'delete-document-16',
  'desktop-16',
  'devices-16',
  'dna-16',
  'document-16',
  'dot-16',
  'download-16',
  'droplets-16',
  'duplicate-16',
  'edit-shape-16',
  'eject-16',
  'ellipsis-16',
  'ellipsis-vertical-16',
  'emoji-16',
  'emoji-sad-16',
  'envelope-16',
  'eraser-16',
  'exclamationmark-16',
  'exclamationmark-2-16',
  'exclamationmark-3-16',
  'eye-16',
  'eye-disabled-16',
  'eye-dropper-16',
  'female-16',
  'film-strip-16',
  'filter-16',
  'finder-16',
  'fingerprint-16',
  'flag-16',
  'folder-16',
  'footprints-16',
  'forward-16',
  'forward-filled-16',
  'fountain-tip-16',
  'full-signal-16',
  'game-controller-16',
  'gauge-16',
  'geopin-16',
  'germ-16',
  'gift-16',
  'glasses-16',
  'globe-01-16',
  'goal-16',
  'hammer-16',
  'hard-drive-16',
  'hashtag-16',
  'heading-16',
  'headphones-16',
  'heart-16',
  'heart-disabled-16',
  'heartbeat-16',
  'highlight-16',
  'hourglass-16',
  'house-16',
  'humidity-16',
  'image-16',
  'important-01-16',
  'info-01-16',
  'italics-16',
  'key-16',
  'keyboard-16',
  'layers-16',
  'leaderboard-16',
  'leaf-16',
  'light-bulb-16',
  'light-bulb-off-16',
  'line-chart-16',
  'link-16',
  'livestream-01-16',
  'livestream-disabled-01-16',
  'lock-16',
  'lock-disabled-16',
  'lock-unlocked-16',
  'logout-16',
  'lorry-16',
  'lowercase-16',
  'magnifying-glass-16',
  'male-16',
  'map-16',
  'mask-16',
  'maximize-16',
  'medical-support-16',
  'megaphone-16',
  'memory-stick-16',
  'microphone-16',
  'microphone-disabled-16',
  'minimize-16',
  'minus-16',
  'minus-circle-16',
  'minus-circle-filled-16',
  'mobile-16',
  'monitor-16',
  'moon-16',
  'moon-down-16',
  'moon-up-16',
  'moonrise-16',
  'mountain-16',
  'mouse-16',
  'move-16',
  'mug-16',
  'mug-steam-16',
  'multiply-16',
  'music-16',
  'network-16',
  'new-document-16',
  'new-folder-16',
  'number-00-16',
  'number-01-16',
  'number-02-16',
  'number-03-16',
  'number-04-16',
  'number-05-16',
  'number-06-16',
  'number-07-16',
  'number-08-16',
  'number-09-16',
  'number-10-16',
  'number-11-16',
  'number-12-16',
  'number-13-16',
  'number-14-16',
  'number-15-16',
  'number-16-16',
  'number-17-16',
  'number-18-16',
  'number-19-16',
  'number-20-16',
  'number-21-16',
  'number-22-16',
  'number-23-16',
  'number-24-16',
  'number-25-16',
  'number-26-16',
  'number-27-16',
  'number-28-16',
  'number-29-16',
  'number-30-16',
  'number-31-16',
  'number-32-16',
  'number-33-16',
  'number-34-16',
  'number-35-16',
  'number-36-16',
  'number-37-16',
  'number-38-16',
  'number-39-16',
  'number-40-16',
  'number-41-16',
  'number-42-16',
  'number-43-16',
  'number-44-16',
  'number-45-16',
  'number-46-16',
  'number-47-16',
  'number-48-16',
  'number-49-16',
  'number-50-16',
  'number-51-16',
  'number-52-16',
  'number-53-16',
  'number-54-16',
  'number-55-16',
  'number-56-16',
  'number-57-16',
  'number-58-16',
  'number-59-16',
  'number-60-16',
  'number-61-16',
  'number-62-16',
  'number-63-16',
  'number-64-16',
  'number-65-16',
  'number-66-16',
  'number-67-16',
  'number-68-16',
  'number-69-16',
  'number-70-16',
  'number-71-16',
  'number-72-16',
  'number-73-16',
  'number-74-16',
  'number-75-16',
  'number-76-16',
  'number-77-16',
  'number-78-16',
  'number-79-16',
  'number-80-16',
  'number-81-16',
  'number-82-16',
  'number-83-16',
  'number-84-16',
  'number-85-16',
  'number-86-16',
  'number-87-16',
  'number-88-16',
  'number-89-16',
  'number-90-16',
  'number-91-16',
  'number-92-16',
  'number-93-16',
  'number-94-16',
  'number-95-16',
  'number-96-16',
  'number-97-16',
  'number-98-16',
  'number-99-16',
  'number-list-16',
  'paperclip-16',
  'paragraph-16',
  'patch-16',
  'pause-16',
  'pause-filled-16',
  'pencil-16',
  'person-16',
  'person-circle-16',
  'person-lines-16',
  'phone-16',
  'phone-ringing-16',
  'pie-chart-16',
  'pill-16',
  'pin-16',
  'pin-disabled-16',
  'play-16',
  'play-filled-16',
  'plug-16',
  'plus-16',
  'plus-circle-16',
  'plus-circle-filled-16',
  'plus-minus-divide-multiply-16',
  'plus-square-16',
  'plus-top-right-square-16',
  'power-16',
  'print-16',
  'question-mark-circle-16',
  'quicklink-16',
  'quotation-marks-16',
  'quote-block-16',
  'racket-16',
  'raindrop-16',
  'raycast-logo-neg-16',
  'raycast-logo-pos-16',
  'receipt-16',
  'redo-16',
  'remove-person-16',
  'repeat-16',
  'replace-16',
  'replace-one-16',
  'reply-16',
  'rewind-16',
  'rewind-filled-16',
  'rocket-16',
  'rosette-16',
  'rotate-anti-clockwise-16',
  'rotate-clockwise-16',
  'rss-16',
  'ruler-16',
  'save-document-16',
  'shield-01-16',
  'short-paragraph-16',
  'shuffle-16',
  'signal-0-16',
  'signal-1-16',
  'signal-2-16',
  'signal-3-16',
  'snippets-16',
  'snowflake-16',
  'soccer-ball-16',
  'speaker-16',
  'speaker-down-16',
  'speaker-high-16',
  'speaker-low-16',
  'speaker-off-16',
  'speaker-on-16',
  'speaker-up-16',
  'speech-bubble-16',
  'speech-bubble-active-16',
  'speech-bubble-important-16',
  'square-ellipsis-16',
  'stacked-bars-1-16',
  'stacked-bars-2-16',
  'stacked-bars-3-16',
  'stacked-bars-4-16',
  'star-16',
  'star-circle-16',
  'star-disabled-16',
  'stars-16',
  'stop-16',
  'stop-filled-16',
  'stopwatch-16',
  'store-16',
  'strike-through-16',
  'sun-16',
  'sunrise-16',
  'swatch-16',
  'switch-16',
  'syringe-16',
  'tack-16',
  'tack-disabled-16',
  'tag-16',
  'temperature-16',
  'tennis-ball-16',
  'terminal-16',
  'text-16',
  'text-cursor-16',
  'text-input-16',
  'text-selection-16',
  'thumbs-down-16',
  'thumbs-down-filled-16',
  'thumbs-up-16',
  'thumbs-up-filled-16',
  'ticket-16',
  'torch-16',
  'train-16',
  'trash-16',
  'tray-16',
  'tree-16',
  'trophy-16',
  'two-people-16',
  'umbrella-16',
  'underline-16',
  'undo-16',
  'upload-16',
  'uppercase-16',
  'video-16',
  'video-disabled-16',
  'wallet-16',
  'wand-16',
  'warning-16',
  'waveform-16',
  'weights-16',
  'wifi-16',
  'wifi-disabled-16',
  'wind-16',
  'windsock-16',
  'wrench-screwdriver-16',
  'wrist-watch-16',
  'x-mark-circle-16',
  'x-mark-circle-filled-16',
  'x-mark-circle-half-dash-16',
  'x-mark-top-right-square-16',
  'xmark-16',
]

function createIconEnum(): Record<string, string> {
  const icons: Record<string, string> = {}

  for (const iconId of iconIds) {
    const name = iconId.replace(/-16$/, '')
    const pascalName = pascalCase(name)
    icons[pascalName] = iconId
  }

  return icons
}

function createIconWithUnicode(): Record<string, string> {
  const icons: Record<string, string> = {}

  for (const iconId of iconIds) {
    const name = iconId.replace(/-16$/, '')
    const pascalName = pascalCase(name)
    icons[pascalName] = getIconShape(iconId)
  }

  return icons
}

export const IconSource = createIconEnum()
export const Icon = createIconWithUnicode()

export function getIconEmoji(icon: string): string {
  // If it's an icon ID (like 'pencil-16'), convert to unicode
  if (iconIds.includes(icon)) {
    return getIconShape(icon)
  }
  // Otherwise assume it's already unicode and return as-is
  return icon
}

/**
 * Extract icon string from any icon format.
 * Handles all Raycast icon formats:
 * - string: direct icon name or emoji
 * - { source: string }: image with source
 * - { source: string, tintColor?: string }: image with tint
 * - { source: { light, dark } }: theme-aware source
 * - { value: ImageLike, tooltip: string }: icon with tooltip
 * - { light: string, dark: string }: theme-aware icon directly
 * - { fileIcon: string }: file icon
 *
 * Returns empty string for unhandled formats (never [object Object])
 */
export function getIconValue(icon: unknown): string {
  if (!icon) {
    return ''
  }

  if (typeof icon === 'string') {
    return getIconEmoji(icon)
  }

  if (typeof icon !== 'object') {
    return ''
  }

  const obj = icon as Record<string, unknown>

  // Handle { value: ..., tooltip: ... } format
  if ('value' in obj && obj.value) {
    return getIconValue(obj.value)
  }

  // Handle { source: ... } format
  if ('source' in obj) {
    const source = obj.source
    if (typeof source === 'string') {
      return getIconEmoji(source)
    }
    // Handle { source: { light, dark } }
    if (typeof source === 'object' && source !== null) {
      const sourceObj = source as Record<string, unknown>
      if ('light' in sourceObj && typeof sourceObj.light === 'string') {
        return getIconEmoji(sourceObj.light)
      }
      if ('dark' in sourceObj && typeof sourceObj.dark === 'string') {
        return getIconEmoji(sourceObj.dark)
      }
    }
    return ''
  }

  // Handle { light, dark } directly on icon
  if ('light' in obj && typeof obj.light === 'string') {
    return getIconEmoji(obj.light)
  }
  if ('dark' in obj && typeof obj.dark === 'string') {
    return getIconEmoji(obj.dark)
  }

  // Handle { fileIcon: string }
  if ('fileIcon' in obj && typeof obj.fileIcon === 'string') {
    return '▤'
  }

  // Unknown format - return empty string instead of [object Object]
  return ''
}

interface IconProps {
  source: string
  tintColor?: string
}

export function IconComponent({ source }: IconProps): any {
  // If it's an icon ID, convert to unicode; otherwise return as-is
  if (iconIds.includes(source)) {
    return getIconShape(source)
  }
  return source
}
