import { test, expect, beforeEach, afterEach } from 'vitest'
import { launchTerminal, Session } from 'tuistory/src'
import { execSync } from 'node:child_process'
import fs from 'node:fs'
import path from 'node:path'

const fixtureDir = path.resolve(__dirname, '../../fixtures/swift-extension')

// Find binary - check debug first, then release
function findSwiftBinary(): string {
  const debugPath = path.join(fixtureDir, 'swift/.build/debug/SwiftAPI')
  const releasePath = path.join(fixtureDir, 'swift/.build/release/SwiftAPI')
  if (fs.existsSync(debugPath)) {
    return debugPath
  }
  if (fs.existsSync(releasePath)) {
    return releasePath
  }
  throw new Error(`Swift binary not found at ${debugPath} or ${releasePath}`)
}

const swiftBinary = findSwiftBinary()

test('swift binary returns items correctly', () => {
  const stdout = execSync(`${swiftBinary} getItems`, { encoding: 'utf-8' })
  expect(JSON.parse(stdout)).toMatchInlineSnapshot(`
    [
      {
        "id": "1",
        "subtitle": "Generated by Swift",
        "title": "Swift Item One",
      },
      {
        "id": "2",
        "subtitle": "From native code",
        "title": "Swift Item Two",
      },
      {
        "id": "3",
        "subtitle": "Fast and safe",
        "title": "Swift Item Three",
      },
    ]
  `)
})

test('swift binary greet function works', () => {
  const stdout = execSync(`${swiftBinary} greet '"World"'`, { encoding: 'utf-8' })
  expect(JSON.parse(stdout)).toMatchInlineSnapshot(`"Hello, World! Greetings from Swift."`)
})

let session: Session

beforeEach(async () => {
  session = await launchTerminal({
    command: 'bun',
    args: ['src/cli.tsx', 'dev', fixtureDir],
    cwd: path.resolve(__dirname, '../..'),
    cols: 70,
    rows: 25,
  })
})

afterEach(() => {
  session?.close()
})

test('swift extension dev mode shows command list', async () => {
  // Wait for command list to appear
  const commandList = await session.text({
    waitFor: (text) => /Swift List/i.test(text),
    timeout: 30000,
  })

  expect(commandList).toMatchInlineSnapshot(`
    "


     Swift Test Extension ───────────────────────────────────────────

     Search commands...

     Commands
    ›List Items Displays a simple list with some items          view
     Swift List Displays a list of items returned by a Swift fu view














     ↵ run command  ↑↓ navigate  ^k actions"
  `)
}, 60000)

test('swift extension runs Swift List command and shows items', async () => {
  // Wait for command list to appear
  await session.text({
    waitFor: (text) => /Swift List/i.test(text),
    timeout: 30000,
  })

  // Navigate down to Swift List (it's the second item)
  await session.press('down')
  
  // Select the Swift List command
  await session.press('return')

  // Wait for Swift items to load and display
  const swiftListOutput = await session.text({
    waitFor: (text) => text.includes('Swift Item One'),
    timeout: 30000,
  })

  expect(swiftListOutput).toMatchInlineSnapshot(`
    "


     Swift Items ────────────────────────────────────────────────────

     Search...

     Items from Swift
    ›Swift Item One Generated by Swift
     Swift Item Two From native code
     Swift Item Three Fast and safe













       ↑↓ navigate  ^k actions"
  `)
}, 60000)
