name: opencode

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]


jobs:
  opencode:
    if: |
      (github.event_name == 'issues' && contains(github.event.issue.body, '/opencode')) ||
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '/opencode'))
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Write auth.json
        run: |
          printf '{"anthropic":{"type":"oauth","refresh":"%s","access":"%s"}}' \
            "${{ secrets.ANTHROPIC_REFRESH_TOKEN }}" \
            "${{ secrets.ANTHROPIC_ACCESS_TOKEN }}" \
            | install -D /dev/stdin ~/.local/share/opencode/auth.json
      - name: Run opencode
        uses: aemr3/opencode/github@dev
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        with:
          model: anthropic/claude-opus-4-1-20250805
          # share: true
          # github_token: xxxx
